import { useState } from 'react'
import DemoPageNote from '../components/DemoPageNote'
import { Link } from 'react-router-dom'
import AiPolicyAssistant from '../components/AiPolicyAssistant'
import Badge from '../components/Badge'
import PolicyCard from '../components/PolicyCard'
import { savePolicy, savePolicySource } from '../data/demoData'
import { createPolicy } from '../services/api'
import type { PolicySource, SpendingPolicy } from '../types'

const inputClass =
  'w-full rounded-lg border border-slate-700 bg-slate-900 px-4 py-2.5 text-white transition-colors duration-200 placeholder:text-slate-600 focus:border-cyan-500 focus:outline-none'

const labelClass = 'mb-1.5 block text-sm text-slate-300'

type Tab = 'manual' | 'ai'

export default function CreatePolicy() {
  const [tab, setTab] = useState<Tab>('manual')
  const [source, setSource] = useState<PolicySource>('MANUAL')

  // Form fields start with the example values from the demo script.
  const [product, setProduct] = useState('1TB SSD')
  const [quantity, setQuantity] = useState('1')
  const [maxPrice, setMaxPrice] = useState('5000')
  const [seller, setSeller] = useState('SecureStore')
  const [warrantyAllowed, setWarrantyAllowed] = useState(false)
  const [receiverWallet, setReceiverWallet] = useState('ALGO-DEMO-WALLET-001')
  const [perTransactionLimit, setPerTransactionLimit] = useState('5000')
  const [dailyLimit, setDailyLimit] = useState('10000')
  const [expiresAt, setExpiresAt] = useState('2026-12-31T23:59')

  const [created, setCreated] = useState<SpendingPolicy | null>(null)
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault()
    setSaving(true)
    setError('')
    setCreated(null)

    try {
      // The backend stores the policy and generates the MG-XXXX id.
      const policy = await createPolicy({
        product,
        quantity: Number(quantity) || 0,
        maxPrice: Number(maxPrice) || 0,
        approvedSeller: seller,
        warrantyAllowed,
        approvedReceiverWallet: receiverWallet,
        perTransactionLimit: Number(perTransactionLimit) || 0,
        dailyLimit: Number(dailyLimit) || 0,
        expiresAt,
      })

      savePolicy(policy)
      savePolicySource('MANUAL')
      setSource('MANUAL')
      setCreated(policy)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not create the policy.')
    } finally {
      setSaving(false)
    }
  }

  /** Called by the AI tab, but only after the human pressed Approve Policy. */
  const handleAiApproved = (policy: SpendingPolicy) => {
    savePolicy(policy)
    savePolicySource('NVIDIA_NIM_ASSISTED')
    setSource('NVIDIA_NIM_ASSISTED')
    setCreated(policy)
  }

  return (
    <section className="mx-auto max-w-6xl px-6 py-12">
      <DemoPageNote />
      <h1 className="text-3xl font-bold text-white">Create Human Spending Policy</h1>
      <p className="mt-2 text-slate-400">
        These are the rules the AI agent must follow. Write them yourself, or describe them
        in plain English and let the AI fill in the form.
      </p>

      {/* Tabs */}
      <div className="mt-8 flex flex-wrap gap-2 border-b border-slate-800">
        <button
          onClick={() => setTab('manual')}
          className={[
            'px-5 py-3 text-sm font-semibold transition-colors duration-200',
            tab === 'manual'
              ? 'border-b-2 border-cyan-500 text-cyan-300'
              : 'text-slate-400 hover:text-white',
          ].join(' ')}
        >
          Manual Policy
        </button>
        <button
          onClick={() => setTab('ai')}
          className={[
            'px-5 py-3 text-sm font-semibold transition-colors duration-200',
            tab === 'ai'
              ? 'border-b-2 border-violet-500 text-violet-300'
              : 'text-slate-400 hover:text-white',
          ].join(' ')}
        >
          Create with AI ✨
        </button>
      </div>

      {tab === 'ai' && (
        <div className="mt-8 grid gap-8 lg:grid-cols-2">
          <AiPolicyAssistant onApproved={handleAiApproved} />

          <div>
            {created ? (
              <div className="space-y-4">
                <div className="rounded-lg border border-emerald-500/40 bg-emerald-500/10 px-5 py-4 font-semibold text-emerald-400">
                  ✓ Policy created successfully — ID {created.id} (generated by the server)
                </div>
                <div className="flex flex-wrap gap-2">
                  <Badge tone="ai">AI Assisted</Badge>
                  <Badge tone="human">Human Approved</Badge>
                </div>
                <PolicyCard policy={created} detailed />
                <Link
                  to="/order"
                  className="inline-block rounded-lg border border-slate-600 px-5 py-2.5 text-sm font-semibold text-white transition-colors duration-200 hover:border-cyan-400 hover:text-cyan-300"
                >
                  Next: let the AI prepare an order →
                </Link>
              </div>
            ) : (
              <div className="flex h-full min-h-[300px] items-center justify-center rounded-xl border border-dashed border-slate-800 p-6 text-center text-slate-500">
                Your approved policy will appear here.
              </div>
            )}
          </div>
        </div>
      )}

      <div className={tab === 'manual' ? 'mt-8 grid gap-8 lg:grid-cols-2' : 'hidden'}>
        {/* Form */}
        <form
          onSubmit={handleCreate}
          className="rounded-xl border border-slate-800 bg-slate-900/60 p-6"
        >
          <div className="grid gap-5 sm:grid-cols-2">
            <div className="sm:col-span-2">
              <label className={labelClass} htmlFor="product">
                Product Name
              </label>
              <input
                id="product"
                className={inputClass}
                value={product}
                onChange={(e) => setProduct(e.target.value)}
                placeholder="1TB SSD"
              />
            </div>

            <div>
              <label className={labelClass} htmlFor="quantity">
                Quantity
              </label>
              <input
                id="quantity"
                type="number"
                min="1"
                className={inputClass}
                value={quantity}
                onChange={(e) => setQuantity(e.target.value)}
                placeholder="1"
              />
            </div>

            <div>
              <label className={labelClass} htmlFor="maxPrice">
                Maximum Price (₹)
              </label>
              <input
                id="maxPrice"
                type="number"
                min="0"
                className={inputClass}
                value={maxPrice}
                onChange={(e) => setMaxPrice(e.target.value)}
                placeholder="5000"
              />
            </div>

            <div className="sm:col-span-2">
              <label className={labelClass} htmlFor="seller">
                Approved Seller
              </label>
              <input
                id="seller"
                className={inputClass}
                value={seller}
                onChange={(e) => setSeller(e.target.value)}
                placeholder="SecureStore"
              />
            </div>

            {/* Warranty toggle */}
            <div className="sm:col-span-2">
              <span className={labelClass}>Warranty Allowed</span>
              <div className="flex gap-3">
                <button
                  type="button"
                  onClick={() => setWarrantyAllowed(true)}
                  className={[
                    'rounded-lg border px-5 py-2 text-sm font-medium transition-colors duration-200',
                    warrantyAllowed
                      ? 'border-emerald-500 bg-emerald-500/10 text-emerald-400'
                      : 'border-slate-700 text-slate-400 hover:border-slate-500',
                  ].join(' ')}
                >
                  Yes
                </button>
                <button
                  type="button"
                  onClick={() => setWarrantyAllowed(false)}
                  className={[
                    'rounded-lg border px-5 py-2 text-sm font-medium transition-colors duration-200',
                    !warrantyAllowed
                      ? 'border-cyan-500 bg-cyan-500/10 text-cyan-300'
                      : 'border-slate-700 text-slate-400 hover:border-slate-500',
                  ].join(' ')}
                >
                  No
                </button>
              </div>
            </div>

            <div className="sm:col-span-2">
              <label className={labelClass} htmlFor="wallet">
                Approved Receiver Wallet
              </label>
              <input
                id="wallet"
                className={inputClass}
                value={receiverWallet}
                onChange={(e) => setReceiverWallet(e.target.value)}
                placeholder="ALGO-DEMO-WALLET-001"
              />
            </div>

            <div>
              <label className={labelClass} htmlFor="perTx">
                Per Transaction Limit (₹)
              </label>
              <input
                id="perTx"
                type="number"
                min="0"
                className={inputClass}
                value={perTransactionLimit}
                onChange={(e) => setPerTransactionLimit(e.target.value)}
                placeholder="5000"
              />
            </div>

            <div>
              <label className={labelClass} htmlFor="daily">
                Daily Spending Limit (₹)
              </label>
              <input
                id="daily"
                type="number"
                min="0"
                className={inputClass}
                value={dailyLimit}
                onChange={(e) => setDailyLimit(e.target.value)}
                placeholder="10000"
              />
            </div>

            <div className="sm:col-span-2">
              <label className={labelClass} htmlFor="expiry">
                Expiry Time
              </label>
              <input
                id="expiry"
                type="datetime-local"
                className={inputClass}
                value={expiresAt}
                onChange={(e) => setExpiresAt(e.target.value)}
              />
            </div>
          </div>

          <button
            type="submit"
            disabled={saving}
            className="mt-6 w-full rounded-lg bg-cyan-500 px-6 py-3 font-semibold text-slate-950 transition-colors duration-200 hover:bg-cyan-400 disabled:opacity-60"
          >
            {saving ? 'Creating…' : 'Create Policy'}
          </button>
        </form>

        {/* Result */}
        <div>
          {error && (
            <div className="mb-4 rounded-lg border border-red-500/40 bg-red-500/10 px-5 py-4 text-red-300">
              {error}
            </div>
          )}

          {created ? (
            <div className="space-y-4">
              <div className="rounded-lg border border-emerald-500/40 bg-emerald-500/10 px-5 py-4 font-semibold text-emerald-400">
                ✓ Policy created successfully — ID {created.id} (generated by the server)
              </div>

              <Badge tone={source === 'MANUAL' ? 'human' : 'ai'}>
                {source === 'MANUAL' ? 'Written by human' : 'AI Assisted'}
              </Badge>

              <PolicyCard policy={created} detailed />

              <Link
                to="/order"
                className="inline-block rounded-lg border border-slate-600 px-5 py-2.5 text-sm font-semibold text-white transition-colors duration-200 hover:border-cyan-400 hover:text-cyan-300"
              >
                Next: See the AI Order →
              </Link>
            </div>
          ) : (
            <div className="flex h-full min-h-[300px] items-center justify-center rounded-xl border border-dashed border-slate-800 p-6 text-center text-slate-500">
              Fill the form and press <span className="mx-1 text-cyan-400">Create Policy</span> to
              see the policy card here.
            </div>
          )}
        </div>
      </div>
    </section>
  )
}
